# name: Publish Python distribution to PyPI

# on:
#   push:
#     tags:
#       - '*'

# jobs:
#   build:
#     name: Build distribution
#     runs-on: magma-runner-set

#     steps:
#     - uses: actions/checkout@v4

#     - name: Install pypa/build
#       run: python -m pip install build --user

#     - name: Build a binary wheel and a source tarball
#       run: python -m build

#     - name: Store the distribution packages
#       uses: actions/upload-artifact@v3
#       with:
#         name: python-package-distributions
#         path: dist/

#   publish-to-pypi:
#     name: Publish Python distribution to PyPI
#     if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
#     needs:
#     - build
#     runs-on: magma-runner-set
#     environment:
#       name: pypi
#       url: https://pypi.org/p/lm_eval
#     permissions:
#       id-token: write  # IMPORTANT: mandatory for trusted publishing

#     steps:
#     - name: Download all the dists
#       uses: actions/download-artifact@v3
#       with:
#         name: python-package-distributions
#         path: dist/
#     - name: Publish distribution to PyPI
#       uses: pypa/gh-action-pypi-publish@release/v1

#   publish-to-testpypi:
#     name: Publish Python distribution to TestPyPI
#     needs:
#     - build
#     runs-on: magma-runner-set

#     environment:
#       name: testpypi
#       url: https://test.pypi.org/p/lm_eval

#     permissions:
#       id-token: write  # IMPORTANT: mandatory for trusted publishing

#     steps:
#     - name: Download all the dists
#       uses: actions/download-artifact@v3
#       with:
#         name: python-package-distributions
#         path: dist/
#     - name: Publish distribution to TestPyPI
#       uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         repository-url: https://test.pypi.org/legacy/